### ISSUE TITLE
Exception java.lang.ExceptionInInitializerError when run using docker-compose

### ISSUE THREAD

**Issue by vipulnewaskar7** [santteegt/spring-cloud-zookeeper-service-discovery-demo#1]
Getting error while microservice image is getting built.
I am attaching the logs generated by docker-compose...

[spring-cloud-zk.log](https://github.com/santteegt/spring-cloud-zookeeper-service-discovery-demo/files/3629801/spring-cloud-zk.log)

**Comment by conorKotwasinski** [comment]
upgrade the maven version in the Dockerfile of each microservice `FROM maven:3.6.1-jdk-8-alpine`
